services:
    server:
        build:
            context: ./server
            dockerfile: Dockerfile
        container_name: server
        ports:
            - '8000:8000'
        networks:
            - app-network
        restart: unless-stopped

networks:
    app-network:
        driver: bridge
