services:
    nginx:
        image: nginx:alpine
        container_name: nginx
        ports:
            - '80:80'
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
            - client
            - server
        networks:
            - app-network
        restart: unless-stopped

    server:
        build:
            context: ./server
            dockerfile: Dockerfile
        container_name: server
        expose:
            - '8000'
        environment:
            - PORT=8000
            - NODE_ENV=production
        networks:
            - app-network
        restart: unless-stopped

    client:
        build:
            context: ./client
            dockerfile: Dockerfile
        container_name: client
        expose:
            - '3000'
        environment:
            - PORT=3000
            - SERVER_URL=http://server:8000
        networks:
            - app-network
        restart: unless-stopped

networks:
    app-network:
        driver: bridge
