services:
    postgres:
        image: postgres:17.4-alpine
        container_name: postgres
        environment:
            POSTGRES_USER: ${POSTGRES_USER:-admin}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-123}
            POSTGRES_DB: ${POSTGRES_DB:-postgres}
        ports:
            - '5432:5432'
        volumes:
            - postgres_data:/var/lib/postgresql/data
        restart: unless-stopped
volumes:
    postgres_data:
