services:
    postgres:
        image: postgres:17.4-alpine
        container_name: postgres
        pull_policy: missing
        environment:
            POSTGRES_USER: ${POSTGRES_USER:-admin}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-123}
            POSTGRES_DB: ${POSTGRES_DB:-postgres}
        ports:
            - '5433:5432'
        volumes:
            - postgres_data:/var/lib/postgresql/data
        restart: unless-stopped

    redis:
        image: redis:alpine
        container_name: redis
        pull_policy: missing
        environment:
            REDIS_USER: ${REDIS_USER:-admin}
            REDIS_PASSWORD: ${REDIS_PASSWORD:-123}
        ports:
            - '6379:6379'
        volumes:
            - redis_data:/data
        restart: unless-stopped

    mosquitto:
        image: eclipse-mosquitto:latest
        container_name: mosquitto
        pull_policy: missing
        ports:
            - '1883:1883'
            - '9001:9001'
        volumes:
            - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
            - ./mosquitto/data:/mosquitto/data
            - ./mosquitto/log:/mosquitto/log
        restart: unless-stopped

volumes:
    postgres_data:
    redis_data:
    mosquitto:
