version: '3.8'

services:
    server:
        build:
            context: .
            dockerfile: Dockerfile
            target: runner
            args:
                NODE_ENV: production
        container_name: smashminton-server
        environment:
            NODE_ENV: production
            PORT: 3001
            # Azure database connections - set these in your .env file
            POSTGRES_HOST: ${POSTGRES_HOST}
            POSTGRES_PORT: ${POSTGRES_PORT:-5432}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
            REDIS_HOST: ${REDIS_HOST}
            REDIS_PORT: ${REDIS_PORT:-6379}
            REDIS_USER: ${REDIS_USER}
            REDIS_PASSWORD: ${REDIS_PASSWORD}
        ports:
            - '3001:3001'
        restart: unless-stopped
        deploy:
            resources:
                limits:
                    memory: 512M
                reservations:
                    memory: 256M
        logging:
            driver: 'json-file'
            options:
                max-size: '10m'
                max-file: '3'
        healthcheck:
            test: ['CMD', 'wget', '--no-verbose', '--tries=1', '--spider', 'http://localhost:3001/health']
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 40s

networks:
    default:
        driver: bridge
